### ISSUE TITLE
VSXD-75 FrontEnd - 클러스터 등록 부분 수정, ratioschedule 수정 - crd서비스 수정 요청

### ISSUE THREAD

**Issue by howjinpark** [MeshManager/Issue#12]
### Issue 이름

FrontEnd - 클러스터 등록 부분 수정, ratioschedule 수정

### 1. 클러스터 등록 부분 수정
make deploy IMG=public.ecr.aws/j8f1l6o6/mesh-agent:v7 UUID="a2c55f3a-fd72-4d04-9e55-b4d505326f29" AGENT_NAME="demo" AGENT_URL="https://www.meshmanagers.com/api/v1/agent" DESIRED_STATE_URL="https://www.meshmanagers.com/api/v1/yaml" CLUSTER_MANAGEMENT_URL="https://www.meshmanagers.com/api/v1/management/clusters" SLACK_WEB_HOOK_URL=" "

그래서 클러스터 등록하기에서 슬랙 아이디랑 슬랙 토큰 값을 받아줘야함

프로메테우스 대신 슬랙 url 받기

------------------------
### 2. ratioschedule 수정
{
  "name": "order-service",
  "namespace": "default",
  "serviceType": "CanaryType",
  "ratio": 10,
  "commitHash": ["v2","v6"],
  "ratioSchedules": [
    {"delayMs": 10000, "newRatio": 30},
    {"delayMs": 15000, "newRatio": 70},
    {"delayMs": 25000, "newRatio": 30}
  ]
}

시간 경과에 따른 비율 조정
꼭 100비율이 될 필요는 없음
그리고 최대 갯수는 100까지 받아도 되긴함

### 체크리스트(Tasks)

- [ ] Task1
- [ ] Task2

### 참조(References)

- Reference1

**Comment by howjinpark** [comment]
### 1. 클러스터 등록 부분 수정

![Image](https://github.com/user-attachments/assets/c9d6e1ed-b0d4-4e65-97ed-859e1edf0dc6)

make deploy IMG=public.ecr.aws/j8f1l6o6/mesh-agent:v4 UUID="424282b0-2e4b-46c9-82cb-0beb3afbd066" AGENT_NAME="aaabbb" AGENT_URL="https://www.meshmanagers.com/api/v1/agent" DESIRED_STATE_URL="https://www.meshmanagers.com/api/v1/crd" CLUSTER_MANAGEMENT_URL="https://www.meshmanagers.com/api/v1/management/clusters" SLACK_WEB_HOOK_URL="ababababa"

슬랙 url 부분을 입력하면 명령어의 SLACK_WEB_HOOK_URL에 입력한 슬랙 url이 들어가짐

-----------
### 2. ratioschedule 수정

![Image](https://github.com/user-attachments/assets/5f0a1974-c848-4f3e-8c8a-06d77cfb1d72)
이렇게 구현했음
기본 설정 값 입력 안하면 시간별 비율 스케쥴링은 설정 못하게 했음

**Comment by howjinpark** [comment]
현재 프론트에서 ratioschedule를    POST /api/v1/crd/{클러스터UUID}/serviceEntity에 보내고 있지만 YAML 생성 로직에서 RatioSchedule을 조회하고 포함시키는 코드가 누락되어 있는 거 같음. 

**IstioRouteServiceImpl.java파일 보면**
구조가 
```
apiVersion: mesh-manager.meshmanager.com/v1
kind: IstioRoute
metadata:
  name: <서비스명>
  namespace: <네임스페이스>
spec:
  services:
    - name: <서비스명>
      namespace: <네임스페이스>
      type: <서비스타입> # CanaryType, StandardType, StickyCanaryType
      commitHashes: 
        - <버전1>
        - <버전2>
      ratio: <트래픽 비율>
      dependencies:
        - name: <의존성 서비스명>
          namespace: <의존성 네임스페이스>
          commitHashes: [<의존성 버전들>]
      darknessReleases:
        - commitHash: <어둠배포 버전>
          ips: [<테스트 IP 목록>]
```
이런식으로 되어 있는데 ratioschedule이 빠짐
이게 에러 원인으로 추측되는데 다른 이유일수도 있음
대응 요망
